### ISSUE TITLE
Suggestion: Continue to cut releases instead of pulling from master branch (similar to Repokid issue)

### ISSUE THREAD

**Issue by kmcquade** [Netflix-Skunkworks/aardvark#109]
Just thought that I'd add this here to aardvark as well since there aren't any releases right now. :) 

Similar to https://github.com/Netflix/repokid

FYI - @mcpeak 

One thing that might help make this easier, especially if you want to push Aardvark and Repokid to PyPi - you can auto-deploy to PyPi by using the TravisCI PyPi provider. This way it isn't as much of a PITA... whenever you tag a new release, it will build, and unless there are non-zero errors, it pushes to PyPi. Saves a bunch of time.

* Example here: https://github.com/salesforce/policy_sentry/blob/master/.travis.yml#L22
* Travis docs: https://docs.travis-ci.com/user/deployment/pypi/

**Comment by patricksanders** [comment]
Thanks for the links @kmcquade. I plan to spend some time on polishing up releases and whatnot in the coming weeks.

**Comment by patricksanders** [comment]
Added PyPI upload on tags to the Travis config in #110 (then fixed it in #111).
