### ISSUE TITLE
plus sign in arn got skipped

### ISSUE THREAD

**Issue by GitOnion** [Netflix-Skunkworks/aardvark#28]
Hi, 

We encountered an issue, likely from an *awsconsole.js* function, *advisor.generateReport*, that ARN with "+" sign in it (as part of the user's name) got parsed to space in the POST request sent to AWS and returned this error message:

`ERROR GenerateServiceLastAccessedDetails arn:aws:iam::123456789012:user/foo+bar. Skipping...
{"readyState":4,"responseText":"{\"errors\":[{\"message\":\"ARN arn:aws:iam::123456789012:user/foo bar does not exist.\",\"code\":\"NoSuchEntity\",\"type\":\"Sender\"}]}","responseJSON":{"errors":[{"message":"ARN arn:aws:iam::123456789012:user/foo bar does not exist.","code":"NoSuchEntity","type":"Sender"}]},"status":404,"statusText":"Not Found"}`

I think this issue is caused by string parsing at AWS end, but wonder what's your opinion and if you have similar issues. Thanks!

**Comment by mcpeak** [comment]
hey @GitOnion this one slipped through somehow.  Did you ever figure out how to work around it?

I agree, this looks like it's failing AWS backend validation.

**Comment by mcpeak** [comment]
Closing old issue.
