### ISSUE TITLE
Fix Travis CI

### ISSUE THREAD

**Issue by JohnVonNeumann** [Netflix-Skunkworks/aardvark#34]
Currently it looks as though there is an issue with Travis CI where the build isn't finding the .travis.yml file itself, so builds don't run. As we can see here:

https://travis-ci.org/Netflix-Skunkworks/aardvark

With even the last merge not having a build run for it.

https://github.com/travis-ci/travis-ci/issues/3936

There's a few issues on this listed in travis, a lot of the time it appears to be a naming issues inside the Travis configuration on the site, so whoever has the creds for it will most likely have to login and make some changes. Comment 2 in the issue linked will explain more.

**Comment by mcpeak** [comment]
Hmm, instructions didn't work but I removed and readded the file and now it looks good.  Thanks!

**Comment by JohnVonNeumann** [comment]
Yep, looks like it's all good now! Cheers
