### ISSUE TITLE
pg_config executable not found

### ISSUE THREAD

**Issue by eric-tucker** [Netflix-Skunkworks/aardvark#5]
On Ubuntu 16.04, following installation instructions (`sudo python setup.py develop`):

```
Running psycopg2-2.7.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-H62v31/psycopg2-2.7.1/egg-dist-tmp-ba8igp
Error: pg_config executable not found.

Please add the directory containing pg_config to the PATH
or specify the full executable path with the option:

    python setup.py build_ext --pg-config /path/to/pg_config build ...

or with the pg_config option in 'setup.cfg'.
error: Setup script exited with 1
[etucker: aardvark]$ 
```

I solved this using https://stackoverflow.com/a/12037133/4075901.

Perhaps this could be documented in the readme?

**Comment by monkeysecurity** [comment]
Thanks Eric.  I'll take a look and see about updating the docs.

@mcpeak

**Comment by mcpeak** [comment]
Made a note in the install section in the README.  Thanks for the report!
