### ISSUE TITLE
Problem installing: deepdiff cannot be installed

### ISSUE THREAD

**Issue by mbaciu-gpsw** [Netflix-Skunkworks/aardvark#58]
I tried installing aardvark as per the docs and got stuck at "python setup.py develop". It complains not being able to install deepdiff.
OS: Ubuntu 18.04.2 LTS
Python: 2.7.15rc1

Steps to reproduce:

```
mkvirtualenv a1
git clone https://github.com/Netflix-Skunkworks/aardvark.git a1
cd a1
python setup.py develop
```
Error messages:
```
Searching for deepdiff>=3.3.0
Reading https://pypi.org/simple/deepdiff/
Downloading https://files.pythonhosted.org/packages/19/6e/47b8ec63a0dea28c7d59e8cfadc4ea11c53ee156100bf42fd63d92f32e65/deepdiff-4.0.6.tar.gz#sha256=55e461f56dcae3dc540746b84434562fb7201e5c27ecf28800e4cfdd17f61e56
Best match: deepdiff 4.0.6
Processing deepdiff-4.0.6.tar.gz
Writing /tmp/easy_install-szmVV3/deepdiff-4.0.6/setup.cfg
Running deepdiff-4.0.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-szmVV3/deepdiff-4.0.6/egg-dist-tmp-g3E7mG
error: Setup script exited with Python 2 is not supported anymore. The last version of DeepDiff that supported Py2 was 3.3.0
```
Full output is here: [setup.log](https://github.com/Netflix-Skunkworks/aardvark/files/3088699/setup.log)

FWIW: had the same issue on Ubuntu 16.04 and Amazon Linux.
As a workaround, I did a ```pip install deepdiff``` (which somehow installs deepdiff-3.3.0, not 4.0.6). Running ```python setup.py develop``` afterwards is successful.

**Comment by monkeysecurity** [comment]
Same thing on SM:

https://github.com/Netflix/security_monkey/pull/1186

I'll PR the `setup.py` file to pin it.
