### ISSUE TITLE
error: Setup script exited with error in funcsigs setup command: Invalid environment marker: python_version<"2.7"

### ISSUE THREAD

**Issue by stylianosrigas-ft** [Netflix-Skunkworks/aardvark#6]
Hey guys, I got this error when running the aardvark setup in Amazon Linux OS. I managed to solve it by running first **pip install pbr funcsigs** locally and then the setup command. I also needed to install some extra packages listing them below:

--postgresql
--postgresql-devel
--python Development tools
--botocore==1.5.0
--pyasn1==0.1.8

**Comment by andrewpbergeron** [comment]
this fixed the issue on the latest AMI: 
pip install --upgrade pip && pip install --upgrade setuptools

**Comment by mcpeak** [comment]
@stylianosrigas-ft can you confirm the above fix please?

**Comment by tsayas** [comment]
Can confirm, fix worked for me on Amazon Linux.

**Comment by stylianosrigas-ft** [comment]
@mcpeak Fix worked for me too.

**Comment by mcpeak** [comment]
Got it, thanks all 👍
